Fix Invalid Array Length error when severity_threshold exceeded
crazy-max/ghaction-container-scan pull request #151
Opened 2024-08-29 21:11 UTC by frankgrimes97

2024-08-29 21:13 UTC, frankgrimes97 commented
This PR attempts to address https://github.com/crazy-max/ghaction-container-scan/issues/150

2024-10-22 17:01 UTC, Rhernandez513 commented
Interested to see this fix go in

2024-10-25 23:12 UTC, crazy-max requested changes
Can you rebase, run `docker buildx bake pre-checkin` to generate dist and squash commits please?

2025-03-29 00:18 UTC, crazy-max approved these changes
LGTM thanks and sorry for the delay!

2025-03-29 00:20 UTC, merged