feature/ignore-unfixed
crazy-max/ghaction-container-scan pull request #160
Opened 2024-10-17 15:55 UTC by Rhernandez513

Adds the --ignore-unfixed CLI flag partially covering #43

All of the steps in ["submitting a pull request" ](https://github.com/crazy-max/ghaction-container-scan/blob/f17494a3e47d86fb17c2c1f89b25049492a82d1d/.github/CONTRIBUTING.md#submitting-a-pull-request)pass except for `docker buildx bake validate` which even after running `docker buildx bake build` and/or deleting `dist/index.js` and `dist/index.js.map` still doesn't resolve

<img width="1147" alt="image" src="https://github.com/user-attachments/assets/f14f6a80-cb37-4cab-a4d7-e5b07a51714e">

2024-10-17 16:16 UTC, DilmurodMak approved these changes

2024-10-25 23:21 UTC, crazy-max requested changes
Needs to update dist with `docker buildx bake pre-checkin`, see https://github.com/crazy-max/ghaction-container-scan/blob/master/.github/CONTRIBUTING.md#submitting-a-pull-request

Can you also squash your commits please?

2024-10-26 06:21 UTC, crazy-max requested changes

2024-10-26 06:21 UTC, crazy-max commented on README.md
> +
Don't think we need a specific usage example just for this but we should have this in the inputs table: https://github.com/crazy-max/ghaction-container-scan?tab=readme-ov-file#inputs

2024-10-26 06:21 UTC, crazy-max commented on README.md
> +  * [`Advanced Security must be enabled for this repository to use code scanning`](#advanced-security-must-be-enabled-for-this-repository-to-use-code-scanning)
Any reason for this change? Can you revert it please?

2024-10-26 06:21 UTC, crazy-max commented on README.md
> +* [About](#about)
Please remove this change, About is before TOC

2024-10-26 06:21 UTC, crazy-max commented on action.yml
> +    required: false
Can you move this right before `annotations`?

2024-10-26 06:21 UTC, crazy-max commented on src/context.ts
> +  ignoreUnfixed?: boolean;
Same as above, move this right before `annotations`

2024-10-26 06:21 UTC, crazy-max commented on src/context.ts
> +    ignoreUnfixed: core.getBooleanInput('ignore_unfixed')
Same here

2024-11-05 15:50 UTC, Rhernandez513 commented on README.md
> +* [About](#about)
```suggestion
```

2024-11-05 15:51 UTC, Rhernandez513 commented on README.md
> +  * [`Advanced Security must be enabled for this repository to use code scanning`](#advanced-security-must-be-enabled-for-this-repository-to-use-code-scanning)
```suggestion
  * [GITHUB_TOKEN Minimum Permissions](#github_token-minimum-permissions)
  * [`Advanced Security must be enabled for this repository to use code scanning`](#advanced-security-must-be-enabled-for-this-repository-to-use-code-scanning)  
```

2025-03-07 20:05 UTC, Rhernandez513 commented on README.md
> +
Change request applied using squashed commits here: [in commit](https://github.com/crazy-max/ghaction-container-scan/pull/160/commits/e6c115f062c4b2f174521bc3370b5586cd04d220)

2025-03-07 20:07 UTC, Rhernandez513 commented on src/context.ts
> +  ignoreUnfixed?: boolean;
Change request applied using squashed commits here (https://github.com/crazy-max/ghaction-container-scan/pull/160/commits/e6c115f062c4b2f174521bc3370b5586cd04d220)

2025-03-07 20:07 UTC, Rhernandez513 commented on src/context.ts
> +    ignoreUnfixed: core.getBooleanInput('ignore_unfixed')
Change request applied using squashed commits here (https://github.com/crazy-max/ghaction-container-scan/pull/160/commits/e6c115f062c4b2f174521bc3370b5586cd04d220)

2025-03-07 20:08 UTC, Rhernandez513 commented
> Needs to update dist with `docker buildx bake pre-checkin`, see https://github.com/crazy-max/ghaction-container-scan/blob/master/.github/CONTRIBUTING.md#submitting-a-pull-request
> 
> Can you also squash your commits please?

Dist updated, all `bake` steps pass, and all comments addressed with squashed commit strategy here (https://github.com/crazy-max/ghaction-container-scan/pull/160/commits/e6c115f062c4b2f174521bc3370b5586cd04d220)

2025-03-29 00:14 UTC, closed without merging

2025-03-29 19:58 UTC, Rhernandez513 commented
@crazy-max  thanks!